### ISSUE TITLE
ecotype selection error 

### ISSUE THREAD

**Issue by mdsnor** [NINAnor/NOFAInsert#33] opened 2017-05-05 10:36 UTC
After selecting an ecotype for one of the species which has an ecotype (example: salmo salar), even if I delete that occurrence row, creating a new occurrence row it is possible to select the ecotype related to the previous update. Should be switching to the initial situation of not available ecotype for a new one.

**Comment by JakobMiksch** [comment] 2017-05-08 14:53
@mdlux I cannot reproduce that

**Comment by JakobMiksch** [comment] 2017-05-10 16:12
I found a error:
![image](https://cloud.githubusercontent.com/assets/15704517/25909015/205c08d8-35ac-11e7-9e1f-4ca677ec140d.png)

Now there is a date in the ecotype field. This should be fixed.

This effect happens, when I change any field of the row above.

**Comment by ninsbl** [comment] 2017-07-30 22:06
Fixed in latest plugin version. Closing the issue. Feel free to reopen if needed.

**Closed as completed by ninsbl** 2017-07-30 22:06 UTC
Labels: bug
